# Generated by Django 6.0.2 on 2026-02-24 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
